week3/template_inheritence/template_app/urls.py
from django.urls import path
from . import views

app_name = "template_app"

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('book/', views.book, name="book"),
    path('menu/', views.menu, name="menu"),
]

week3/template_inheritence/template_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('template_app.urls')),
]

week3/template_inheritence/template_app/models.py
from django.db import models

# Create your models here.

week3/template_inheritence/template_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request, "index.html")
def menu(request):
    return render(request, "menu.html")
def about(request):
    return render(request, "about.html")
def book(request):
    return render(request, "book.html")

week3/template_inheritence/templates/about.html
<!-- Add code to extend base.html file -->
{% extends 'base.html' %}
<!-- Add code to load static content -->
{% load static %}

<!-- Begin block content -->
{% block content %}
<p\> About Us</p>
    <p\> This is an About page for Little Lemon </p\>
    {% endblock %}
    <!-- End block content -->

week3/template_inheritence/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>Little Lemon</title>
  <meta name="description" content="A brief description" />
  <meta name="author"
    content="Based in Chicago, Illinois, Little Lemon is a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist." />

  <!-- Load favicon -->
  <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}" />

  <!-- Include your CSS files here -->
  <link rel="preload" as="style" href="{% static 'css/style.css' %}" onload="this.rel = 'stylesheet'" />

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
    rel="stylesheet" />
</head>

<body>
  <!-- Add include tag -->.
  {% include 'partials/_header.html' %}

  <main>
    <!-- Begin block content -->
    {% block content %}
    {% endblock content %}
    <!-- End block content -->
  </main>


</body>

</html>

week3/template_inheritence/templates/book.html
<!-- Add code to extend base.html file -->
{% extends 'base.html' %}
<!-- Add code to load static content -->
{% load static %}

<!-- Begin block content -->
{% block content %}
<p\> Book</p>
    <p\> This is a Book page for Little Lemon </p\>
    {% endblock %}
    <!-- End block content -->

week3/template_inheritence/templates/index.html
<!-- Add code to extend base.html file -->
{% extends 'base.html' %}

<!-- Add code to load static content -->
{% load static %}

<!-- Begin block content -->
{% block content %}
<p\> Home</p>
    <p\> This is a Home page for Little Lemon </p\>
    {% endblock %}
    <!-- End block content -->

week3/template_inheritence/templates/menu.html
<!-- Add code to extend base.html file -->
{% extends 'base.html' %}
<!-- Add code to load static content -->
{% load static %}

<!-- Begin block content -->
{% block content %}
<p\> Menu</p>
    <p\> This is a Menu page for Little Lemon </p\>
    {% endblock %}
    <!-- End block content -->

week3/template_inheritence/templates/partials/_header.html
<!-- Add code to load static content-->
{% load static %}

<header>
    <img src="{% static 'img/logo.png' %}" />
</header>
<nav>
    <ul>
        <li><a href="{% url 'template_app:home' %}">Home</a></li>
        <li><a href="{% url 'template_app:about' %}">About</a></li>
        <li><a href="{% url 'template_app:menu' %}">Menu</a></li>
        <li><a href="{% url 'template_app:book' %}">Book</a></li>
    </ul>
</nav>